- name: zabbix
  matchers:
    - part: headers.set-cookie
      type: word
      words:
        - "zbx_sessionid="
- name: vBulletin
  matchers:
    - part: headers.set-cookie
      type: word
      words:
        - "bbsessionhash="
        - "bblastactivity="
        - "bblastvisit="

- name: pyLoad
  matchers:
    - part: title
      type: word
      words:
        - "Login - pyLoad"