name: Run code on push
on:
  push:
    branches:
      - main
jobs:
  run-code:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "Running script..."
